### ISSUE TITLE
Reading private scheme keys using the private keys paths crashes on non-xml files

### ISSUE THREAD

**Issue by reinier-chipsoft** [privacybydesign/irmago#43]
We use the IRMA server in a kubernetes container. The private key of a scheme is mounted using a Kubernetes secret. These secrets automatically add some hidden files to the mounted directory, so the directory includes files that are not a private key. The IRMA server crashes on these files, because it assumes all files in the directory are private scheme key files, even ones not having an '.xml' extension. It would be better if the IRMA server would ignore all files not having an '.xml' extension.

Also the documentation on this point seems invalid. According to the documentation the files should be named issuername-count.xml. But actually, they need to be named schemename-issuername.xml. The count is derived from the xml contents.

**Comment by sietseringers** [comment]
Thanks! This should now be fixed: the server now skips non-key files (emitting a log message that it did so). The correct filenames are `schemename.issuername.xml`, with a dot. I'll update the documentation soon.

**Comment by reinier-chipsoft** [comment]
Great.

**Comment by reinier-chipsoft** [comment]
This fix is not correct I'm afraid. The added condition:

`filepath.Ext(filename) != ".xml" && strings.Count(filename, ".") != 3`

... should use an OR instead of an AND.

I happen to have a file with three dots which still crashes the server.

**Comment by sietseringers** [comment]
Apologies, it should work now.

**Comment by reinier-chipsoft** [comment]
Oops, we both didn't see that the key files have two dots, not three. 

So now I get this log:

"Skipping non-private key file irma-demo.ChipSoft.xml encountered in private keys path"

**Comment by sietseringers** [comment]
D'oh. Should be really fixed now (I've tested it more carefully this time). I've also added that it will always skip hidden files (beginning with `.`) even if they have the right extension and amount of dots.
